Repository travis-ci/terraform-config, pull requests merged in 2018-04, with the labels that each got.

#403 Configure nat-conntracker dynamic bits via redis
  bin/nat-conntracker-configure
  gce-production-net-1/main.tf
  gce-production-net-1/nat-conntracker.env
  gce-production-net-2/main.tf
  gce-production-net-2/nat-conntracker.env
  gce-production-net-3/main.tf
  gce-production-net-3/nat-conntracker.env
  gce-production-net-4/main.tf
  gce-production-net-4/nat-conntracker.env
  gce-production-net-5/main.tf
  gce-production-net-5/nat-conntracker.env
  gce-staging-net-1/main.tf
  gce-staging-net-1/nat-conntracker.env
  modules/gce_net/main.tf
Labels: awaiting-review

#406 Remove us-central1-c from GCE job VM zones
  gce-production-1/worker.env
  gce-production-2/worker.env
  gce-production-3/worker.env
  gce-production-4/worker.env
  gce-production-5/worker.env
Labels: awaiting-review

#407 Drop usage of us-central1-c more effectively
  gce-production-1/instance-counts.auto.tfvars
  gce-production-1/main.tf
  gce-production-1/worker.env
  gce-production-2/instance-counts.auto.tfvars
  gce-production-2/main.tf
  gce-production-2/worker.env
  gce-production-3/instance-counts.auto.tfvars
  gce-production-3/main.tf
  gce-production-3/worker.env
  gce-production-4/instance-counts.auto.tfvars
  gce-production-4/main.tf
  gce-production-4/worker.env
  gce-production-5/instance-counts.auto.tfvars
  gce-production-5/main.tf
  gce-production-5/worker.env
Labels: awaiting-review

#412 Replace some spaces with tabs in terraform-common.mk
  terraform-common.mk
Labels: in progress

#411 A few minor tweaks to the .ensure-git target
  terraform-common.mk
Labels: awaiting-review, in progress

#400 Backfill a license file whoops!
  LICENSE.md
Labels: awaiting-review

#398 Remove long-unused gce-production-6 graph dir
  gce-production-6/Makefile
  gce-production-6/main.tf.disabled
  gce-production-6/worker.env
Labels: awaiting-review

#410 Remove transitional tfw bits
  assets/tfw/etc/apt/apt.conf.d/10recommends
  assets/tfw/etc/rsyslog.d/50-default.conf
  assets/tfw/etc/rsyslog.d/65-papertrail.conf
  assets/tfw/etc/ssh/ssh_config
  assets/tfw/etc/ssh/sshd_config
  assets/tfw/etc/sudoers
  assets/tfw/etc/sudoers.d/90-group-sudo
  assets/tfw/usr/local/bin/travis-docker-wrapper
  assets/tfw/usr/local/bin/travis-full-hostname
  assets/tfw/usr/local/bin/travis-tfw-combined-env
  assets/tfw/var/tmp/travis-tfw-bootstrap.bash
  modules/packet_network/cloud-config.yml.tpl
  modules/packet_network/cloud-init.bash
  modules/packet_worker/cloud-config.yml.tpl
  modules/packet_worker/cloud-init.bash
  packet.mk
  terraform-common.mk
Labels: awaiting-review, in progress

#414 Add packet production bits
  dns-production-0/main.tf
  modules/packet_worker/cloud-init.bash
  packet-production-1/Makefile
  packet-production-1/main.tf
  packet-production-1/worker.env
  packet-production-net-1/Makefile
  packet-production-net-1/main.tf
Labels: awaiting-review, in progress

#415 Add DNS records for nat.linux-containers.travisci.net
  dns-production-0/main.tf
Labels: awaiting-review, in progress

#413 Bump default terraform version v0.11.5 => v0.11.7
  terraform-common.mk
Labels: awaiting-review, in progress

#419 Remove now-unnecessary TERRAFORM overrides
  dns-production-0/Makefile
  gce-production-net-1/Makefile
  gce-production-net-2/Makefile
  gce-production-net-3/Makefile
  gce-production-net-4/Makefile
  gce-production-net-5/Makefile
  gce-staging-net-1/Makefile
Labels: awaiting-review, in progress

#421 Bump Docker API version to match available
  packet-production-1/worker.env
  packet-staging-1/worker.env
Labels: awaiting-review

#425 Correct data source
  dns-production-0/main.tf
Labels: in progress

#426 Set bash SHELL for all
  aws.mk
  packet.mk
  terraform-common.mk
Labels: in progress

#427 Rework provisioning for Packet NAT & Workers
  Makefile
  assets/bits/terraform-user-bootstrap.bash
  bin/heroku-dump-shell-config
  modules/packet_network/main.tf
  modules/packet_network/nat-dynamic-config.bash
  modules/packet_network/nat-dynamic-config.yml.tpl
  modules/packet_network/nat-user-data.bash.tpl
  modules/packet_worker/cloud-init.bash
  modules/packet_worker/main.tf
  packet-production-net-1/main.tf
  packet-staging-1/main.tf
  packet-staging-net-1/main.tf
Labels: awaiting-review, in progress

#428 Updates to packet production to match module APIs
  packet-production-1/main.tf
  packet-production-net-1/main.tf
Labels: awaiting-review, in progress

#429 Reject forwarded packets to Packet metadata API
  modules/packet_network/nat-dynamic-config.bash
  modules/packet_worker/cloud-init.bash
Labels: awaiting-review, in progress

#433 Minor tweaks to get a fresh install working
  macstadium-pod-1/main.tf
  macstadium-pod-1/workers.tf
  modules/macstadium_dhcp_server/install-dhcpd.sh
Labels: awaiting-review, in progress

#434 Clean up old Mac graph dirs.
  macstadium-shared-1/.example.env
  macstadium-shared-1/.terraform-validate-flags
  macstadium-shared-1/Makefile
  macstadium-shared-1/main.tf.disabled
  macstadium-shared-2/.example.env
  macstadium-shared-2/.terraform-validate-flags
  macstadium-shared-2/Makefile
  macstadium-shared-2/main.tf.disabled
Labels: in progress

#418 Add rules to log and drop spoofed packets
  modules/packet_network/nat-dynamic-config.bash
Labels: in progress

#430 Packet worker tweaks based on latest production behavior
  assets/bits/maybe-reboot.bash
  assets/bits/terraform-user-bootstrap.bash
  modules/aws_asg/cloud-init.bash
  modules/gce_worker/cloud-init.bash
  modules/packet_network/nat-dynamic-config.bash
  modules/packet_worker/dynamic-config.bash
  modules/packet_worker/dynamic-config.yml.tpl
  modules/packet_worker/main.tf
  modules/packet_worker/user-data.bash.tpl
  packet-production-1/main.tf
  packet-staging-1/main.tf
Labels: awaiting-review, in progress
